owner: tryton
repo: upptime

sites:
  - name: Tryton
    url: https://www.tryton.org
    icon: https://cdn.tryton.org/static/images/favicon.ico

status-website:
  cname: status.tryton.org
  logoUrl: https://downloads-cdn.tryton.org/images/logo.svg
  name: Tryton's Upptime
  favicon: https://cdn.tryton.org/static/images/favicon.ico
  faviconSvg: https://downloads-cdn.tryton.org/images/logo.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Tryton
      href: https://www.tryton.org/
